// Generated by CoffeeScript 1.8.0
var app, bodyParser, botlogic, express, port;

express = require('express');

bodyParser = require('body-parser');

botlogic = require('./botlogic');

app = express();

port = process.env.PORT || 3000;

require('coffee-script/register');

app.use(bodyParser.urlencoded({
  extended: true
}));

app.get('/', function(req, res) {
  res.status(200).send('Hello world!');
});

app.use(function(err, req, res, next) {
  console.error(err.stack);
  res.status(400).send(err.message);
});

app.listen(port, function() {
  console.log('Slack bot listening on port ' + port);
});
